services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: NutritIA-bot
    # environment:
    #   - OPENAI_API_KEY=${OPENAI_API_KEY}
    #   - NUTRITIONIX_APP_ID=${NUTRITIONIX_APP_ID}
    #   - NUTRITIONIX_APP_KEY=${NUTRITIONIX_APP_KEY}
    #   - NUTRITIONIX_API_URL=${NUTRITIONIX_API_URL}
    networks:
      - NutritIA-network
    # volumes:
    #   - ./src:/app/src
    #   - ./data:/app/data
    
networks:
  NutritIA-network:
    driver: bridge